apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crijan-main-ingress
  namespace: crijan-core
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "crijan.in"
        - "www.crijan.in"
        - "api.crijan.in"
        - "*.previews.crijan.in"
      secretName: crijan-tls-secret
  rules:
    - host: "crijan.in"
      http: &http_rules
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crijan-frontend
                port: { number: 80 }
    - host: "www.crijan.in"
      http: *http_rules
    - host: "api.crijan.in"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port: { number: 80 }
    - host: "*.previews.crijan.in"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crijan-me-proxy
                port: { number: 80 }
