# k8s/proxy/proxy-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crijan-me-proxy
  namespace: crijan-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crijan-me-proxy
  template:
    metadata:
      labels:
        app: crijan-me-proxy
    spec:
      # ✅ ADDED THIS BLOCK TO UNLOCK DOCKER HUB
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: crijan-me-proxy
          image: chetan930/crijan-me-proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: crijan-shared-config
          env:
            - name: REDIS_URL
              value: "redis://redis-0.redis.crijan-core.svc.cluster.local:6379"
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: crijan-me-proxy
  namespace: crijan-core
spec:
  selector:
    app: crijan-me-proxy
  ports:
    - port: 80
      targetPort: 80
